---
title: "Analysis of SARS-CoV2 cases in a pediatric hospital"
author: "Marta Mainetti"
date: "`r date()`"
format: 
  html:
    toc: true
    code-fold: show
    code-tools: true
    df-print: paged
---


# Import libraries and prepare setting

```{r, warning = FALSE, message = FALSE}
library(cowplot)
library(dplyr)
library(ggplot2)
library(ggpointdensity)
library(medicaldata)
library(skimr)
library(unibeCols)
```

# Load data

```{r}
covid_testing_raw <- medicaldata::covid_testing
```

```{r}
covid_testing <- covid_testing_raw %>% 
  mutate(subject_id = as.character(subject_id)) %>% 
  filter(result != "invalid")

head(covid_testing)
```


# Preliminary analysis

```{r}
skim_without_charts(covid_testing)
table(covid_testing$result)
```


# Data visualization

```{r}
ggplot(data = covid_testing, aes(x = age, y = result, fill = result)) +
  geom_boxplot() +
  scale_fill_manual(breaks = c("positive", "negative"),
                    values = c(unibeRedS()[2], unibeMustardS()[2])) +
  theme(legend.position = "none")
```


```{r}
p1 <- ggplot(data = covid_testing, aes(x = pan_day, y = age, col = result)) +
  geom_point(size = 1) +
  scale_color_manual(breaks = c("positive", "negative"),
                    values = c(unibeRedS()[2], unibeMustardS()[2])) +
  labs(x = "Days after start of pandemic", y = "Age", 
       col = "Test result") +
  theme(legend.position = "bottom")

p2 <- ggplot(data = covid_testing, aes(x = pan_day, y = age)) +
  geom_pointdensity(size = 1) +
  labs(x = "Days after start of pandemic", y = "Age") +
  theme(legend.position = "bottom")

cowplot::plot_grid(plotlist = list(p1, p2), align = "h", labels = c("A", "B"))
```

# Aggregated data

```{r}
g <- covid_testing %>% group_by(pan_day) %>% 
  summarize(cases_per_day = sum(result == "positive"))

ggplot(data = g, aes(x = pan_day, y = cases_per_day)) +
  geom_line() +
  geom_smooth(method = "lm", se = FALSE, color = "dodgerblue",
              linetype = 2) +
  labs(x = "Days from start of the pandemic",
       y = "Daily incidence")
```


# Conclusion